services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expressdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: express_app
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/expressdb
      JWT_SECRET: supersecret
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    command: npm run dev

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
